
{% set data = load_setup_py_data() %}

package:
    name: levelset
    
    version: {{ data['version'] }}

source:
    path: ../

build:
    number: '0'

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        # dependencies are defined in setup.py
        {% for dep in data['install_requires'] %}
        - {{ dep.lower() }}
        {% endfor %}

about:
    home: https://github.com/ajinkyakadu125/levelset
    license_file: LICENSE.md
    summary: "3D level-set method for high-resolution electron tomography"

extra:
    maintainers:
        - Ajinkya Kadu
